[project]
name = "data-engineering-assessment-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-powertools>=3.0.0",
    "python-decouple>=3.8",
]
